# ==========================================
# Configurações do Banco de Dados (Supabase)
# ==========================================
spring.datasource.url=jdbc:postgresql://db.fzlyfseucyumqzlieslj.supabase.co:6543/postgres
spring.datasource.username=postgres
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Configurações do JPA / Hibernate
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "update" faz o Spring criar/atualizar as tabelas automaticamente baseado no código Java
spring.jpa.hibernate.ddl-auto=update
# Exibe as queries SQL no console (excelente para depuração e aprendizado)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true